# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0]. Caches the 'stack' build
# directory to speed subsequent compilations.
#
language: minimal
dist: xenial

cache:
  timeout: 600
  directories:
    - $HOME/.stack
    - $HOME/.local/bin
    - $TRAVIS_BUILD_DIR/.stack-work

before_cache:
  # - rm -rf $(stack path --local-install-root)/bin
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
    packages: &apt_packages
      - alex-3.1.7
      - freeglut3-dev
      - happy-1.19.5
      - libgmp-dev

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.5
      compiler: "GHC 8.6"

    - env: GHC=8.4.3
      compiler: "GHC 8.4"

    - env: GHC=8.2.2
      compiler: "GHC 8.2"

    - env: GHC=8.0.2
      compiler: "GHC 8.0"

    - env: GHC=7.10.3
      compiler: "GHC 7.10"

    - env: GHC=7.8.4
      compiler: "GHC 7.8"

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-stack.sh

  # ghc-8.4+ require libffi7
  - export LD_LIBRARY_PATH=$(stack exec ghc -- --print-libdir)/rts:$LD_LIBRARY_PATH

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version

install:
  - export FLAGS="--fast --jobs=2 --no-terminal --no-copy-bins --no-interleaved-output"
  - stack build ${FLAGS} --test --dry-run

  - travis_retry stack build ${FLAGS} --test --only-dependencies

script:
  - stack build ${FLAGS} --test --haddock --no-haddock-deps

after_success:
  - source .travis/update-accelerate-buildbot.sh

